name: CI/CD for Vercel-Next

on:
  push:
    branches: [master]

jobs:
  push-to-personal-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push to personal repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.MYREPOSITORYKEY }}
        with:
          source-directory: '.'
          destination-github-username: JONGHYUNVAN
          destination-repository-name: test
          user-email: ${{ secrets.MYEMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
